import EventEmitter from 'events';
import { TRconOptions } from '../types';
export declare class Rcon extends EventEmitter {
    readonly id: number;
    private client?;
    private readonly host;
    private readonly port;
    private readonly password;
    private readonly pingDelay?;
    private readonly autoReconnect?;
    private readonly autoReconnectDelay?;
    private readonly chatListeners?;
    private readonly soh;
    private readonly logger;
    private commandId;
    private responseBody;
    private connected;
    private lastDataBuffer;
    private timerPing?;
    private responseTaskQueue;
    private lastCommands;
    constructor(options: TRconOptions);
    init(): Promise<unknown>;
    close(): Promise<unknown>;
    execute(command: string): Promise<string>;
    getListPlayers(): Promise<import("../types").TPlayer[]>;
    getListSquads(): Promise<import("../types").TSquad[]>;
    getCurrentMap(): Promise<import("../types").TMap>;
    getNextMap(): Promise<import("../types").TMap>;
    getServerInfo(): Promise<import("../types").TServerInfo | undefined>;
    private connect;
    private reconnect;
    private onData;
    private onResponse;
    private onConnected;
    private onAuth;
    private onCloseConnection;
    private onErrorConnection;
    private encode;
    private decode;
    private badPacket;
    private ping;
}
